# Generated by Django 2.1.5 on 2019-01-25 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notification_perms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None),
        ),
    ]
