# Generated by Django 2.1.5 on 2019-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followers'),
        ('articles', '0004_articlerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_articles', to='profiles.Profile'),
        ),
    ]
