# Generated by Django 2.1.5 on 2019-01-30 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_reportarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_stats', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='read_stats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readstats',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
        migrations.AddField(
            model_name='readstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
