# Generated by Django 2.1.5 on 2019-01-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userProfile',
            new_name='author',
        ),
    ]
