# Generated by Django 2.1.5 on 2019-01-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190124_1741'),
        ('comments', '0002_auto_20190129_1211'),
    ]

    operations = [
    ]
